List product
dcquan97/rails_6_shopping pull request #2
Opened 2020-02-14 07:43 UTC by dcquan97

2020-02-14 07:53 UTC, rubykachu requested changes

2020-02-14 07:53 UTC, rubykachu commented on app/controllers/products_controller.rb
> +    session[:product_id] = @product.id
Khong su dung session

2020-02-14 07:53 UTC, rubykachu commented on app/helpers/products_helper.rb
> +module ProductsHelper
Khong dung thi xoa.
Khong su dung rails scaffold de tao file

2020-02-14 07:53 UTC, rubykachu commented on test/controllers/products_controller_test.rb
> +require 'test_helper'
Xoa file nay

2020-02-14 07:53 UTC, rubykachu commented on app/views/products/index.html.erb
> +          <% @products.each do |product| %>
khong su dung each
Dung render collection

2020-02-14 07:53 UTC, rubykachu commented on app/views/products/index.html.erb
> +  <footer class="py-5 bg-dark">
tach ra layout

2020-02-16 03:41 UTC, dcquan97 commented
e ms add gem kaminari vao list_product

2020-02-17 01:20 UTC, tm-minhtang requested changes

2020-02-17 01:20 UTC, tm-minhtang commented on app/views/layouts/application.html.erb
> +    <title><%= title_here = title.presence || 'Shopping' %></title>
title.presence || 'Shopping'

2020-02-17 01:20 UTC, tm-minhtang commented on app/views/products/index.html.erb
> +  <% end %>
content_for :title, Shop Homepage

2020-02-17 01:20 UTC, tm-minhtang commented on app/views/layouts/application.html.erb
> +      <%= render "users/shared/navigation" %>
navigation không thuộc folder users. Hãy để trong shared

2020-02-17 01:20 UTC, tm-minhtang commented on app/views/products/index.html.erb
> +        <%= render 'shared/list_product' %>
list_products không thuộc trong shared. Đặt nó trong folder products có tên file là products.html.erb

2020-02-17 01:20 UTC, tm-minhtang commented on app/views/shared/_list_product.html.erb
> +  <% @products.each do |product| %>
Dùng render collection, không sử dụng each trong view

2020-02-17 01:20 UTC, tm-minhtang commented on app/views/shared/_list_product.html.erb
> +  <% @products.each do |product| %>
https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections

2020-02-17 01:20 UTC, tm-minhtang commented on app/views/users/shared/_navigation.html.erb
> +        <%= render 'users/shared/sign_in' %>
không thuộc folder users. Hãy để trong shared. Tương tự cái bên dưới

2020-02-17 02:06 UTC, dcquan97 commented on app/views/layouts/application.html.erb
> +    <title><%= title_here = title.presence || 'Shopping' %></title>
e merge qua quen xoa :)) sr a

2020-02-17 02:22 UTC, dcquan97 commented
e fix lai roi do a Minh

2020-02-17 02:54 UTC, tm-minhtang requested changes

2020-02-17 02:54 UTC, tm-minhtang commented on app/controllers/application_controller.rb
> +  end
remove this function

2020-02-17 02:54 UTC, tm-minhtang commented on app/controllers/products_controller.rb
> +    @product = Product.find(params[:id])
Xử lý lỗi nếu id ko tồn tại

2020-02-17 02:54 UTC, tm-minhtang commented on app/views/layouts/application.html.erb
> +    <title><%= title.presence || 'Shopping' %></title>
yield(:title).presence ||  'HomePage'

2020-02-17 02:54 UTC, tm-minhtang commented on app/views/products/_product.html.erb
> +<% @products.each do |product| %>
ko dung each

2020-02-17 06:18 UTC, dcquan97 commented
e sua lai roi a Minh

2020-02-17 06:20 UTC, merged